In [1]:
import torch
import numpy as np

### Initialising Empty Tensors / Vectors

In [2]:
_scalar = torch.empty(1)
print(_scalar)

tensor([0.])


In [3]:
_1DVector = torch.empty(2)
print(_1DVector)

tensor([0., 0.])


In [4]:
_2Dvector = torch.empty(2,2)
print(_2Dvector)

tensor([[0., 0.],
        [0., 0.]])


In [5]:
_MultiDimDvector = torch.empty(3,3,2)
print(_MultiDimDvector)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])


### Initializing tensor with values

In [6]:
_randTensor = torch.rand(2,2)
print(_randTensor)

tensor([[0.3984, 0.3364],
        [0.3740, 0.4964]])


In [7]:
_zeroTensor = torch.zeros(2,2)
print(_zeroTensor)

tensor([[0., 0.],
        [0., 0.]])


In [8]:
# check the type and size() of the tensor
print(_randTensor.dtype)
print(_randTensor.size())

torch.float32
torch.Size([2, 2])


In [9]:
_tensorFromList = torch.tensor(np.array([1.8, 4.6, 2.6, 3.9]))
print(_tensorFromList)
print(_tensorFromList.dtype)
print(_tensorFromList.size())

tensor([1.8000, 4.6000, 2.6000, 3.9000], dtype=torch.float64)
torch.float64
torch.Size([4])


### Basic operations on tensors

In [10]:
X = torch.rand(2,2)
y = torch.rand(2,2)

## Adding tensors

_tensorAddition = X + y
print("Tensor Addition1: ",_tensorAddition)

_tensorAddition = torch.add(X, y)
print("Tensor Addition2: ", _tensorAddition)

_tensorMul = torch.matmul(X, y)
print("Tensor Multiplication:", _tensorMul)

Tensor Addition1:  tensor([[1.5909, 0.5918],
        [1.0625, 1.5108]])
Tensor Addition2:  tensor([[1.5909, 0.5918],
        [1.0625, 1.5108]])
Tensor Multiplication: tensor([[0.9025, 0.5277],
        [0.6340, 0.5791]])


### Selecting specific row and column

In [11]:
_randomTensor = torch.rand(8,5)
print(_randomTensor)

# selecting all rows and a specific column, in this case its column 2
print(_randomTensor[:, 2])

# selecting all columns and a specific row, in this case its row 2
print(_randomTensor[2, :])

tensor([[0.2154, 0.1361, 0.6874, 0.5702, 0.3433],
        [0.8499, 0.8222, 0.9080, 0.4943, 0.6427],
        [0.9569, 0.5620, 0.6172, 0.4587, 0.1549],
        [0.6876, 0.2989, 0.2408, 0.9825, 0.8142],
        [0.8193, 0.6893, 0.6530, 0.7383, 0.8879],
        [0.6427, 0.9909, 0.3234, 0.6303, 0.2454],
        [0.8015, 0.2088, 0.5688, 0.5403, 0.1047],
        [0.9631, 0.8342, 0.3299, 0.5223, 0.3990]])
tensor([0.6874, 0.9080, 0.6172, 0.2408, 0.6530, 0.3234, 0.5688, 0.3299])
tensor([0.9569, 0.5620, 0.6172, 0.4587, 0.1549])


### Reshaping the tensor

In [12]:
_randomTensor = torch.rand(4,5)
print(_randomTensor)

print(_randomTensor.view(20)) # reshape to 1D tensor
print(_randomTensor.view(-1, 4)) # dynamycally reshape according to the total number of elements

tensor([[0.0617, 0.9025, 0.5954, 0.8899, 0.2291],
        [0.7858, 0.4394, 0.5564, 0.5479, 0.8759],
        [0.1303, 0.9205, 0.5072, 0.7089, 0.7277],
        [0.0679, 0.0284, 0.2195, 0.7885, 0.4136]])
tensor([0.0617, 0.9025, 0.5954, 0.8899, 0.2291, 0.7858, 0.4394, 0.5564, 0.5479,
        0.8759, 0.1303, 0.9205, 0.5072, 0.7089, 0.7277, 0.0679, 0.0284, 0.2195,
        0.7885, 0.4136])
tensor([[0.0617, 0.9025, 0.5954, 0.8899],
        [0.2291, 0.7858, 0.4394, 0.5564],
        [0.5479, 0.8759, 0.1303, 0.9205],
        [0.5072, 0.7089, 0.7277, 0.0679],
        [0.0284, 0.2195, 0.7885, 0.4136]])


### Convert Numpy arrays to torch tensor & vice-versa

In [13]:
# Create a 2x3 NumPy array
arr_np = np.array([[1, 2, 3], [4, 5, 6]])

# Convert NumPy array to PyTorch tensor
tensor_torch = torch.from_numpy(arr_np)

# Print the PyTorch tensor
print(tensor_torch)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [14]:
# Create a 2x3 PyTorch tensor
tensor_torch = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Convert PyTorch tensor to NumPy array
arr_np = tensor_torch.numpy()

# Print the NumPy array
print(arr_np)

[[1 2 3]
 [4 5 6]]


### Check if GPU is available

In [15]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device) # move the numpy array to GPU
    z = x + y
    z = z.to('cpu') # move the numpy array back to CPU
    print(z)
else:
    print('No CUDA GPU available on the Machine')

No CUDA GPU available on the Machine
