In [10]:
import torch
import numpy as np

### Initialising Empty Tensors / Vectors

In [2]:
_scalar = torch.empty(1)
print(_scalar)

tensor([0.])


In [3]:
_1DVector = torch.empty(2)
print(_1DVector)

tensor([0., 0.])


In [4]:
_2Dvector = torch.empty(2,2)
print(_2Dvector)

tensor([[0., 0.],
        [0., 0.]])


In [6]:
_MultiDimDvector = torch.empty(3,3,2)
print(_MultiDimDvector)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])


### Initializing tensor with values

In [7]:
_randTensor = torch.rand(2,2)
print(_randTensor)

tensor([[0.6154, 0.1916],
        [0.0298, 0.9228]])


In [8]:
_zeroTensor = torch.zeros(2,2)
print(_zeroTensor)

tensor([[0., 0.],
        [0., 0.]])


In [9]:
# check the type and size() of the tensor
print(_randTensor.dtype)
print(_randTensor.size())

torch.float32
torch.Size([2, 2])


In [14]:
_tensorFromList = torch.tensor(np.array([1.8, 4.6, 2.6, 3.9]))
print(_tensorFromList)
print(_tensorFromList.dtype)
print(_tensorFromList.size())

tensor([1.8000, 4.6000, 2.6000, 3.9000], dtype=torch.float64)
torch.float64
torch.Size([4])


### Basic operations on tensors

In [18]:
X = torch.rand(2,2)
y = torch.rand(2,2)

## Adding tensors

_tensorAddition = X + y
print("Tensor Addition1: ",_tensorAddition)

_tensorAddition = torch.add(X, y)
print("Tensor Addition2: ", _tensorAddition)

_tensorMul = torch.matmul(X, y)
print("Tensor Multiplication:", _tensorMul)

Tensor Addition1:  tensor([[0.7521, 1.5726],
        [1.5451, 1.7344]])
Tensor Addition2:  tensor([[0.7521, 1.5726],
        [1.5451, 1.7344]])
Tensor Multiplication: tensor([[0.6754, 0.6986],
        [1.2151, 1.2886]])


### Selecting specific row and column

In [24]:
_randomTensor = torch.rand(8,5)
print(_randomTensor)

# selecting all rows and a specific column, in this case its column 2
print(_randomTensor[:, 2])

# selecting all columns and a specific row, in this case its row 2
print(_randomTensor[2, :])

tensor([[0.9142, 0.1158, 0.2695, 0.7451, 0.4152],
        [0.6099, 0.1600, 0.4836, 0.6164, 0.5235],
        [0.0304, 0.2665, 0.2854, 0.3350, 0.0855],
        [0.6923, 0.2678, 0.3411, 0.6688, 0.7480],
        [0.3420, 0.8140, 0.3093, 0.5449, 0.9698],
        [0.5648, 0.4177, 0.1319, 0.2778, 0.1631],
        [0.9215, 0.8578, 0.8370, 0.4246, 0.4276],
        [0.8108, 0.7406, 0.3365, 0.1490, 0.0518]])
tensor([0.2695, 0.4836, 0.2854, 0.3411, 0.3093, 0.1319, 0.8370, 0.3365])
tensor([0.0304, 0.2665, 0.2854, 0.3350, 0.0855])


### Reshaping the tensor

In [30]:
_randomTensor = torch.rand(4,5)
print(_randomTensor)

print(_randomTensor.view(20)) # reshape to 1D tensor
print(_randomTensor.view(-1, 4)) # dynamycally reshape according to the total number of elements

tensor([[0.6663, 0.5060, 0.5663, 0.4178, 0.4369],
        [0.7370, 0.0947, 0.7268, 0.4268, 0.6994],
        [0.5449, 0.5490, 0.5540, 0.2136, 0.1773],
        [0.2034, 0.2736, 0.5803, 0.7570, 0.8834]])
tensor([0.6663, 0.5060, 0.5663, 0.4178, 0.4369, 0.7370, 0.0947, 0.7268, 0.4268,
        0.6994, 0.5449, 0.5490, 0.5540, 0.2136, 0.1773, 0.2034, 0.2736, 0.5803,
        0.7570, 0.8834])
tensor([[0.6663, 0.5060, 0.5663, 0.4178],
        [0.4369, 0.7370, 0.0947, 0.7268],
        [0.4268, 0.6994, 0.5449, 0.5490],
        [0.5540, 0.2136, 0.1773, 0.2034],
        [0.2736, 0.5803, 0.7570, 0.8834]])


### Convert Numpy arrays to torch tensor & vice-versa

In [31]:
# Create a 2x3 NumPy array
arr_np = np.array([[1, 2, 3], [4, 5, 6]])

# Convert NumPy array to PyTorch tensor
tensor_torch = torch.from_numpy(arr_np)

# Print the PyTorch tensor
print(tensor_torch)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [32]:
# Create a 2x3 PyTorch tensor
tensor_torch = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Convert PyTorch tensor to NumPy array
arr_np = tensor_torch.numpy()

# Print the NumPy array
print(arr_np)

[[1 2 3]
 [4 5 6]]
